### PR TITLE
WIP: Another approach...

### PR DESCRIPTION
**Pull request by devknoll**
I'm not really satisfied with the direction the `next` branch is heading, design wise. I'm not super thrilled with just pulling out all of the queries and tucking them into single RootContainer. Doing that means your entire page would be locked down if e.g. your inner most container changed. That's seems like a terrible user experience.

At the same time, wrapping everything in a root container + the above is also bad. Double queries getting issued isn't good either and, despite just being a bug in Relay, doesn't seem compatible with the direction Relay is headed.

So I went back to the drawing board and came up with this. It's basically an inverted portal (of @ryanflorence modal fame). Every time it finds a nested Relay.Container, it mounts a new RootContainer for that section on a new React tree. Instead of rending into it though, it passes the element descriptions that would be rendered back to the original DOM tree to be rendered (with correct context and everything).

@cpojer @taion I'd love it if you took a look at this. The code is horrid at the moment, but I'd like to see if you think it's a good strategy and @taion make sure it fits your use case. It _should_. You two also have write access to this repo should you decide you want to start a coup instead :wink:

### CODE REVIEW

**Comment by taion** [comment]
I think there might be a simpler approach if we want to get the best of both worlds. I think the algorithm would look something like

1. Build a list of `{queries, params}`.
2. On route change, compare the old list and the new list (can we get away with just shallow comparison here? I think we can).
3. At the point where those two lists differ, insert a new `RootContainer` that aggregates all queries from that point onward
4. Remove the old queries from the aggregated queries on the root `RootContainer`

The way I think this could work is that you usually have two `RootContainer`s at a time - a "root" one and a "stem" one. For the initial render, we only have the "root" `RootContainer`. After that, whenever we have a route change, we place the "stem" `RootContainer` at the point where the components change - and that restricts the "loading" behavior to just that branch of the tree, while keeping everything above it (hopefully) untouched.

This is sort of like a cheap, dirty version of React's tree diffing algorithm... maybe... if you glance at it a bit askew, but I think if we can make the "diff" part work, is relatively simple conceptually, and keeps some of the nicer features of the current approach.

**Comment by devknoll** [comment]
@taion Have you done much with `setVariables` yet? Would a two root container approach still work, or would the whole page get locked down?

**Comment by taion** [comment]
I'm not sure what you mean. Isn't `setVariables` somewhat orthogonal?

**Comment by devknoll** [comment]
I'm imagining a situation where you have:

```js
<App>
  <Header>
  </Header>
  <Newsfeed/>
</App>
```

If the Newsfeed supported infinite scrolling using Relay pagination with `setVariables`, and `setVariables` triggered a RootContainer `renderLoading`*, then we're back in the same boat as batching everything up into one RootContainer.

\* I'm not sure that it does, but I haven't tested.

**Comment by taion** [comment]
That almost seems like an orthogonal problem regardless, though. It seems like it ought to be possible to `setVariables` without worrying about where your `RootContainer`s are placed. Even without routing, that would be an issue, but I don't think it'd be an issue with this package.

I think all we need to solve might be to just avoid updating the top-level `RootContainer` unnecessarily.

**Comment by devknoll** [comment]
Why do you dislike RootContainer's so much, @taion? :wink:

**Comment by taion** [comment]
Well, the main thing regarding an initial render is that lifecycle management seems like it'd be a lot easier if there were a single `RootContainer` from where I could do it, which seems like it could be nice for server-side rendering or whatever. Plus it'd be nice just to have as few elements as possible.

The other concern I have with this portal-based approach is that it seems like it'd be quite tricky to use with server-side rendering, whenever that lands.

**Comment by devknoll** [comment]
Good point. It's kinda tough to try to reason about support server rendering support without an official story from Relay though.

That being said, it still feels like it wouldn't be a huge jump to support it from here. We'll definitely need some way to aggregate all of the queries and execute them (this is also something that can be done today without a RootContainer -- and you shouldn't be required to render one either).

Then a branch on creating the portal -- if we're on the server, we can set the `Container` content prop directly from the Relay store for rendering. Otherwise on the client, it'll create the containers and read from the cache + keep rendering what we got from the server.

All of that being said, I think we're in a good spot. I think the API we've settled on for integrating with react-router is great and don't see it changing much. Right now, I'm just sorta focused on getting a good front end experience, and I think that *requires* multiple RootContainers, or duplicating a lot of the work they do. I think the server rendering bridge can be crossed when it gets here.

**Comment by taion** [comment]
To go into a bit more detail, what I'm thinking is something like this. Denote root containers _R_, components _C_, and queries _Q_. Suppose our current state of the world is:

_R1_({_Q1_, _Q2_, _Q3_, _Q4_}) > (_C1_, _Q1_) > (_C2_, _Q2_) > (_C3_, _Q3_) > (_C4_, _Q4_)

Suppose we initiate a route change that replaces that last part of the branch with (_C3_', _Q3_'). It seems like we could then render:

_R1_({_Q1_, _Q2_}) > (_C1_, _Q1_) > (_C2_, _Q2_) > _R2_({_Q3_'}) > (_C3_', _Q3_')

What I expect this to do is that _R1_ will remain in the "fetched" state because we already have _Q1_ and _Q2_, and _C1_ and _C2_ corresponding won't be locked, while _R2_ can do just the unique fetch for the new _Q3'_.

**Comment by taion** [comment]
The thing that bothers me about trying too hard to deal with this, though, is that it seems like we're handling it in the wrong place. There should be some generic way to deal with asynchronously resolving data for React Router, with something like `AsyncProps` or whatever that will do... something, I'm not sure what.

The issue of having to deal with data that's only available asynchronously to complete a route transition isn't specific to dealing with Relay, so it feels a little weird to solve it here. Ideally this would be something that React Router provides for us that we can hook into.

My thoughts with the current solution that has the single top-level `RootContainer` is that your behavior is no worse than what you'd get if you weren't using an SPA, plus you can defer any slow queries, so... wait

**Comment by taion** [comment]
What do you mean by

>Doing that means your entire page would be locked down if e.g. your inner most container changed.

I don't think that's quite right - can't verify right now but that doesn't seem like what I expect to see happen.

It looks like the `RootContainer` sets `shouldUpdate` to false on its `StaticContainer`, but that just means that updates from Relay don't make it to the contained child... which is fine because there aren't any, since the `RootContainer` is still loading the data.

Unless I'm misunderstanding something, everything else on your page should continue to work.

**Comment by devknoll** [comment]
Sorry, can't respond to everything right now, but I mean: if you have one RootContainer, and you override `renderLoading`, any changes to the route or component will cause renderLoading to run.

To give a concrete example, my current app with the latest npm package shows a spinner in renderLoading. Every time you navigate pages, the entire page disappears so that this spinner can show up, then the entire page comes back (being remounted!) once the data comes in. 

Doing anything else would require reimplementing functionality that RootContainer already provides :-/

**Comment by taion** [comment]
Hmm. Yeah - I see what you mean; it's tough right now to e.g. show a loading spinner for only one part of the page. If you don't set `renderLoading`, you get nice behavior... but no loading spinner, which is not always ideal. Let me think about this a little bit.

**Comment by devknoll** [comment]
Is that nice behavior though? On a slow or mobile connection, you'll get no indication that anything is happening for several seconds until the page pops in :-/

**Comment by taion** [comment]
You're right. I have an idea though! Hold on.

**Pull request closed without merging**
